#!/usr/bin/env php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-07-02 
 */

use Net\Bazzline\Component\Cli\Readline\ManagerFactory;

require_once __DIR__ . '/../vendor/autoload.php';

class Basic
{
    public function bar()
    {
        $this->cli(__METHOD__, func_get_args());
    }

    public function foo()
    {
        $this->cli(__METHOD__, func_get_args());
    }

    /**
     * @param string $identifier
     * @param array $arguments
     */
    private function cli($identifier, array $arguments = array())
    {
        fputs(STDOUT, 'called: ' . $identifier . ' with arguments: ' . var_export($arguments, true) . PHP_EOL);
    }
}

$basic  = new Basic();
$dump   = function ($arguments = null) {
    if (is_null($arguments)) {
        echo 'called without any arguments' . PHP_EOL;
    } else {
        var_dump($arguments);
    }
};

$configuration = array(
    'cli'   => array(
        'bar' => array($basic, 'bar'),
        'foo' => array($basic, 'foo')
    ),
    'clear' => 'readline_clear_history',
    'echo'  => function ($arguments = null) {
        if (is_null($arguments)) {
            echo 'called without any arguments' . PHP_EOL;
        } else {
            echo var_export($arguments, true) . PHP_EOL;
        }
    },
    'dump'  => $dump
);

$factory    = new ManagerFactory();
$manager    = $factory->create();

$manager->setConfiguration($configuration);
$manager->setPrompt('basic: ');
$manager->run();